mcl_3dl:
  map_frame: "map"
  fake_imu: true
  lpf_step: 1.0
  acc_lpf_step: 128.0

  # map
  map_downsample_x: 0.1
  map_downsample_y: 0.1
  map_downsample_z: 0.1
  downsample_x: 0.05
  downsample_y: 0.05
  downsample_z: 0.05
  update_downsample_x: 0.3
  update_downsample_y: 0.3
  update_downsample_z: 0.3
  map_update_interval_t: 2.0
  dist_weight_x: 2.0
  dist_weight_y: 2.0
  dist_weight_z: 6.0
  global_localization_grid_lin: 0.1
  global_localization_grid_ang: 0.5

  num_particles: 500
  # covariance
  init_var_x: 1.0
  init_var_y: 1.0
  init_var_z: 0.5
  init_var_yaw: 0.05
  resample_var_x: 0.2
  resample_var_y: 0.1
  resample_var_z: 0.05
  resample_var_yaw: 0.005
  resample_var_pitch: 0.01
  resample_var_roll: 0.01
  expansion_var_x: 0.2
  expansion_var_y: 0.2
  expansion_var_z: 0.2
  expansion_var_yaw: 0.01
  expansion_var_pitch: 0.01
  expancion_var_roll: 0.01
  acc_var: 0.7853981634 # 45deg

  match_ratio_thresh: 0.5
  odom_err_lin_lin: 0.7
  odom_err_lin_ang: 0.4 #dekita:0.1 default:0.05
  odom_err_ang_lin: 0.2 #dekita:1.0 default:0.05
  odom_err_ang_ang: 0.1 #dekita:1.0 default:0.05
  odom_err_integ_lin_tc: 10.0
  odom_err_integ_lin_sigma: 100.0
  odom_err_ang_tc: 10.0
  odom_err_integ_ang_sigma: 100 #default:100

  jump_dist: 1.0 #0.01 default:1.0
  jump_ang: 1.57 #default:1.57
  fix_dist: 0.2
  fix_ang: 0.1
  bias_var_dist: 2.0
  bias_var_ang: 1.57
  skip_measure: 1
  accum_cloud: 1
  total_accum_cloud_max: 10
  match_output_interval_interval: 0.2
  tf_tolerance: 0.05
  match_output_dist: 0.3
  umatch_output_dist: 0.5
  publish_tf: true
  output_pcd: false
  map_chunk: 30.0

  likelihood:
    clip_near: 0.8 #0.5
    clip_far: 40.0 #10.0 old-ver:15.0
    clip_z_min: -10.0
    clip_z_max: 30.0
    match_dist_min: 2.0
    match_output_dist: 0.2
    match_dist_flat: 0.05
    match_weight: 18.0
    # num_points:
    num_points_global: 0.0
  # beam:
    # clip_beam_near:
    # clip_far:
    # clip_z_min:
    # clip_z_max:
    # num_points:
    # beam_likelihood: 0.2
    # ang_total_ref:
obj_to_pointcloud:
  frame_id: "map"
  points_per_meter_sq: 1200.0
  downsample_grid: 0.1
pcd_to_pointcloud:
  frame_id: "map"
  latch: true
