# you can change following params
predict_time: 3.7
dist_from_head_to_obj: 0.3
angle_to_goal_th: 0.26
velocity_th_for_stop_behind_obj: 0.15
slow_velocity_th: 0.1


# you should change this param in default_full.launch
target_velocity: 1.0

# you shouldn't change following params
dt: 0.1
angle_resolution: 0.0087
dist_to_goal_th: 0.3
turn_direction_th: 0.1
velocity_samples: 3
yawrate_samples: 20
