# you can change following params
PREDICT_TIME: 3.0
OBSTACLE_COST_GAIN: 1.0
TO_GOAL_COST_GAIN: 0.8
SPEED_COST_GAIN: 0.4
PATH_COST_GAIN: 0.4
SLOW_VELOCITY_TH: 0.1


# you should change this param in default_full.launch
TARGET_VELOCITY: 1.0

# you shouldn't change following params
DT: 0.1
ANGLE_RESOLUTION: 0.087
GOAL_THRESHOLD: 0.3
TURN_DIRECTION_THRESHOLD: 0.1
OBS_RANGE: 2.5
VELOCITY_SAMPLES: 3
YAWRATE_SAMPLES: 20
ANGLE_TO_GOAL_TH: 1.3
SIM_DIRECTION: 1.57
